app/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from werkzeug.security import generate_password_hash, check_password_hash
from ..db import get_db_connection
import psycopg2

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        name = request.form['name']
        study_group = request.form['study_group']
        telegram = request.form['telegram']
        
        hashed_password = generate_password_hash(password)

        conn = get_db_connection()
        cur = conn.cursor()
        
        try:
            cur.execute("INSERT INTO users (username, password, name, study_group, telegram) VALUES (%s, %s, %s, %s, %s)", 
                       (username, hashed_password, name, study_group, telegram))
            conn.commit()
            flash("Регистрация успешна! Теперь войдите в свой аккаунт.", "success")
            return redirect(url_for('auth.login'))
        except psycopg2.Error as e:
            flash("Ошибка регистрации. Возможно, пользователь уже существует.", "error")
            return redirect(url_for('auth.register'))
        finally:
            cur.close()
            conn.close()
    
    return render_template('register.html')

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        conn = get_db_connection()
        cur = conn.cursor()

        cur.execute("SELECT id, password, role FROM users WHERE username = %s", (username,))
        user = cur.fetchone()
        
        cur.close()
        conn.close()

        if user and check_password_hash(user[1], password):
            session['user_id'] = user[0]
            session['username'] = username
            session['role'] = user[2]
            flash("Вход выполнен успешно!", "success")
            return redirect(url_for('equipment.arenda'))
        else:
            flash("Неверное имя пользователя или пароль.", "error")

    return render_template('login.html')

@auth_bp.route('/logout')
def logout():
    session.pop('user_id', None)
    session.pop('role', None)
    flash("Вы вышли из аккаунта.", "info")
    return redirect(url_for('main.index'))

app/routes/equipment.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from ..db import get_db_connection

equipment_bp = Blueprint('equipment', __name__)

@equipment_bp.route('/arenda')
@equipment_bp.route('/arenda/<int:page>')
def arenda(page=1):
    if 'user_id' not in session:
        flash("Пожалуйста, войдите в систему.", "error")
        return redirect(url_for('auth.login'))

    user_role = session.get('role', 'user')
    items_per_page = 5  # Количество элементов на странице

    conn = get_db_connection()
    cur = conn.cursor()
    
    # Получаем общее количество записей
    cur.execute("SELECT COUNT(*) FROM equipment")
    total_items = cur.fetchone()[0]

    cur.execute("SELECT COUNT(*) FROM equipment WHERE amount != 0")
    total_items_without_zero_amount = cur.fetchone()[0]
    
    # Получаем записи для текущей страницы
    offset = (page - 1) * items_per_page
    #cur.execute("SELECT * FROM equipment ORDER BY id LIMIT %s OFFSET %s", (items_per_page, offset))
    cur.execute("""
    SELECT 
        equipment.id, 
        equipment.title, 
        equipment.description, 
        equipment_types.name AS type_name,
        equipment.amount
    FROM equipment
    JOIN equipment_types ON equipment.type_id = equipment_types.id
    WHERE equipment.amount != 0
    ORDER BY equipment.id
    LIMIT %s OFFSET %s
    """, (items_per_page, offset))
    equipment_list = cur.fetchall()
    
    cur.close()
    conn.close()

    equipment_list = [
    {'id': row[0], 'title': row[1], 'description': row[2], 'type': row[3], 'amount': row[4]}
    for row in equipment_list
    ]

    total_pages = (total_items_without_zero_amount + items_per_page - 1) // items_per_page

    return render_template('arenda.html', 
                         equipment=equipment_list, 
                         role=user_role,
                         current_page=page,
                         total_pages=total_pages)

@equipment_bp.route('/add_equipment', methods=['GET', 'POST'])
def add_equipment():
    if 'user_id' not in session or session.get('role') != 'admin':
        #flash("Доступ запрещен.", "error")
        return redirect(url_for('equipment.arenda'))

    if request.method == 'POST':
        type_ = request.form['type']
        title = request.form['title']
        description = request.form.get('description', '')
        amount = request.form['amount']

        conn = get_db_connection()
        cur = conn.cursor()

        cur.execute("""
            SELECT id
            FROM equipment_types
            WHERE name = %s
                    
        """,(type_,)
        )
        type_id = cur.fetchone()

        cur.execute("""
            INSERT INTO equipment (title, description, type_id, amount) 
            VALUES (%s, %s, %s, %s)
        """, (title, description, type_id, amount))
        conn.commit()
        cur.close()
        conn.close()

        flash("Снаряжение успешно добавлено.", "success")
        return redirect(url_for('equipment.arenda'))

    return render_template('add_equipment.html')

@equipment_bp.route('/edit_equipment/<int:id>', methods=['GET', 'POST'])
def edit_equipment(id):
    if 'user_id' not in session:
        flash("Пожалуйста, войдите в систему.", "error")
        return redirect(url_for('auth.login'))
    
    conn = get_db_connection()
    cur = conn.cursor()

    if request.method == 'POST':
        type_ = request.form['type']
        title = request.form['title']
        description = request.form.get('description', '')
        amount = request.form['amount']

        cur.execute("""
            SELECT id
            FROM equipment_types
            WHERE name = %s
                    
        """,(type_,)
        )
        type_id = cur.fetchone()

        cur.execute("""
            UPDATE equipment SET type_id = %s, title = %s, description = %s, amount = %s
           
            WHERE id = %s
                    
        """,(type_id, title, description, amount, id)
        )
        conn.commit()
        cur.close()
        conn.close()

        flash("Снаряжение успешно обновлено.", "success")
        return redirect(url_for('equipment.arenda'))

    # GET-запрос: загружаем данные для редактирования
    cur.execute("""
                SELECT t.name, e.title, e.description, e.amount
                FROM equipment e
                JOIN equipment_types t ON e.type_id = t.id
                WHERE e.id = %s                
                """, (id,))
    equipment = cur.fetchone()
    cur.close()
    conn.close()

    equipment_data = {
        'id': id,
        'type': equipment[0],
        'title': equipment[1],
        'description': equipment[2] if equipment[2] else '',
        'amount': equipment[3]
    }
    return render_template('edit_equipment.html', equipment=equipment_data)



@equipment_bp.route('/delete_equipment/<int:equipment_id>', methods=['POST'])
def delete_equipment(equipment_id):
    if 'user_id' not in session:
        flash("Пожалуйста, войдите в систему.", "error")
        return redirect(url_for('auth.login'))

    try:
        conn = get_db_connection()
        cur = conn.cursor()
        
        # Удаляем запись по id
        cur.execute("DELETE FROM equipment WHERE id = %s", (equipment_id,))
        conn.commit()
        
        cur.close()
        conn.close()
        
        flash("Снаряжение успешно удалено!", "success")
    except Exception as e:
        flash(f"Ошибка при удалении: {str(e)}", "error")
    
    return redirect(url_for('equipment.arenda'))

app/routes/reservation.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from ..db import get_db_connection

reservation_bp = Blueprint('reservation', __name__)

@reservation_bp.route('/reserve', methods=['GET', 'POST'])
def reserve():
    if 'user_id' not in session:
        flash("Сначала войдите в систему", "error")
        return redirect(url_for('auth.login'))

    # Для GET-запроса извлекаем equipment_id из query-параметров URL
    equipment_id = request.args.get('equipment_id')

    # Для POST-запроса извлекаем equipment_id из формы
    if request.method == 'POST':
        equipment_id = request.form.get('equipment_id')

    # Проверяем, что equipment_id передан и является числом
    if not equipment_id or not equipment_id.isdigit():
        flash("Неверный ID снаряжения.", "error")
        return redirect(url_for('equipment.arenda'))

    conn = get_db_connection()
    cur = conn.cursor()

    # Загружаем данные об оборудовании
    cur.execute("SELECT id, title FROM equipment WHERE id = %s", (equipment_id,))
    equipment = cur.fetchone()

    # Проверяем, что снаряжение найдено
    if not equipment:
        flash("Снаряжение не найдено.", "error")
        cur.close()
        conn.close()
        return redirect(url_for('equipment.arenda'))

    if request.method == 'POST':
        reservation_goal = request.form['reservation_goal']
        reservation_date = request.form['reservation_date']
        date_take_equipment = request.form['date_take_equipment']

        user_id = session['user_id']
        cur.execute("SELECT username, name, study_group, telegram FROM users WHERE id = %s", (user_id,))
        user = cur.fetchone()

        if user:
            username, name, study_group, telegram = user

            cur.execute("""
                INSERT INTO reservations 
                (reservation_goal, reservation_date, date_take_equipment, equipment_id, user_id, reserve_status_id) 
                VALUES (%s, %s, %s, %s, %s, %s)
            """, (reservation_goal, reservation_date, date_take_equipment, equipment[0], user_id, 1))

            conn.commit()
            flash("Снаряжение успешно забронировано!", "success")
        else:
            flash("Не удалось найти данные пользователя", "error")

        cur.close()
        conn.close()
        return redirect(url_for('equipment.arenda'))

    cur.close()
    conn.close()
    return render_template('reserve.html', equipment={'id': equipment[0], 'title': equipment[1]})

@reservation_bp.route('/view_reservations', methods=['GET', 'POST'])
def view_reservations():
    if 'user_id' not in session:
        flash("Пожалуйста, войдите в систему.", "error")
        return redirect(url_for('auth.login'))

    conn = get_db_connection()
    cur = conn.cursor()

    # Обработка POST-запроса для изменения статуса бронирования
    if request.method == 'POST':
        

        reservation_id = request.form.get('reservation_id')
        action = request.form.get('action')

        # Проверяем, что reservation_id и action переданы
        if not reservation_id or not reservation_id.isdigit():
            flash("Неверный ID бронирования.", "error")
            cur.close()
            conn.close()
            return redirect(url_for('reservation.view_reservations'))

        if action not in ['approve', 'reject', 'delete', 'confirm_delivery', 'confirm_return', 'confirm_no_return']:
            flash("Неверное действие.", "error")
            cur.close()
            conn.close()
            return redirect(url_for('reservation.view_reservations'))

        # Проверяем, существует ли бронирование
        cur.execute("SELECT id FROM reservations WHERE id = %s", (reservation_id,))
        reservation = cur.fetchone()
        if not reservation:
            cur.execute("SELECT id FROM reservations_history WHERE id = %s", (reservation_id,))
            reservation = cur.fetchone()
            if not reservation:
                flash("Бронирование не найдено.", "error")
                cur.close()
                conn.close()
                return redirect(url_for('reservation.view_reservations'))
        
         # Если действие — удаление
        if action == 'delete':

            # Удаляем бронирование
            cur.execute("DELETE FROM reservations WHERE id = %s", (reservation_id,))
            cur.execute("DELETE FROM reservations_history WHERE id = %s", (reservation_id,))
            conn.commit()
            flash("Бронирование успешно удалено.", "success")
            cur.close()
            conn.close()
            return redirect(url_for('reservation.view_reservations'))

        if action == 'confirm_delivery':
            new_status = 4
            new_status_text = 'Выдано'
            cur.execute("UPDATE reservations SET reserve_status_id = %s WHERE id = %s", (new_status, reservation_id))
            cur.execute("""UPDATE equipment SET amount = amount - 1 
                WHERE id = (
                SELECT equipment_id
                FROM reservations
                WHERE id = %s)""", (reservation_id,))
            conn.commit()

            flash(f"Снаряжение {new_status_text.lower()}.", "success")

        if action == 'confirm_return':
            new_status = 5
            new_status_text = 'Возвращено'
            cur.execute("UPDATE reservations SET reserve_status_id = %s WHERE id = %s", (new_status, reservation_id))
            cur.execute("""UPDATE equipment SET amount = amount + 1 
                WHERE id = (
                SELECT equipment_id
                FROM reservations
                WHERE id = %s)""", (reservation_id,))
            
            conn.commit()

            flash(f"Снаряжение {new_status_text.lower()}.", "success")
        
        if action == 'confirm_no_return':
            new_status = 6
            new_status_text = 'Не возвращено'
            cur.execute("UPDATE reservations SET reserve_status_id = %s WHERE id = %s", (new_status, reservation_id))
            
            conn.commit()

            flash(f"Снаряжение {new_status_text.lower()}.", "error")

        if action == 'approve':
            new_status = 2
            new_status_text = 'Одобрено'
            cur.execute("UPDATE reservations SET reserve_status_id = %s WHERE id = %s", (new_status, reservation_id))
            conn.commit()

            flash(f"Бронирование {new_status_text.lower()}.", "success")


        if action == 'reject':
            new_status = 3
            new_status_text = 'Отклонено'
            cur.execute("UPDATE reservations SET reserve_status_id = %s WHERE id = %s", (new_status, reservation_id))
            conn.commit()

            flash(f"Бронирование {new_status_text.lower()}.", "error")

        cur.close()
        conn.close()
        return redirect(url_for('reservation.view_reservations'))

    # Получаем все записи с нужным статусом
    cur.execute("""
        SELECT * FROM reservations
        WHERE reserve_status_id IN (3, 5, 6)
    """)
    rows_to_move = cur.fetchall()

    # Получаем имена столбцов
    colnames = [desc[0] for desc in cur.description]

    # Формируем список плейсхолдеров под INSERT
    placeholders = ', '.join(['%s'] * len(colnames))
    columns = ', '.join(colnames)

    # Вставляем и удаляем записи
    for row in rows_to_move:
        # Вставка в reservations_history
        cur.execute(f"""
            INSERT INTO reservations_history ({columns})
            VALUES ({placeholders})
        """, row)

        # Удаление из reservations по id
        reservation_id = row[colnames.index('id')]
        cur.execute("""
            DELETE FROM reservations WHERE id = %s
        """, (reservation_id,))

    # Сохраняем изменения
    conn.commit()

    # Обработка GET-запроса для отображения списка бронирований
    if session.get('role') == 'admin':
        # Для админа показываем все бронирования
        cur.execute("""
            SELECT r.id, u.username, u.name, u.study_group, u.telegram, r.reservation_goal, 
                   r.reservation_date, r.date_take_equipment, r_statuses.name, e.title, et.name
            FROM reservations r
            JOIN equipment e ON r.equipment_id = e.id
            JOIN equipment_types et ON e.type_id = et.id
            JOIN users u ON r.user_id = u.id
            JOIN reserve_statuses r_statuses ON r.reserve_status_id = r_statuses.id
            ORDER BY r.reservation_date DESC
        """)
    else:
        # Для пользователя только его бронирования
        cur.execute("""
            SELECT r.id, u.username, u.name, u.study_group, u.telegram, r.reservation_goal, 
                   r.reservation_date, r.date_take_equipment, r_statuses.name, e.title, et.name
            FROM reservations r
            JOIN equipment e ON r.equipment_id = e.id
            JOIN equipment_types et ON e.type_id = et.id
            JOIN users u ON r.user_id = u.id
            JOIN reserve_statuses r_statuses ON r.reserve_status_id = r_statuses.id
            WHERE u.username = %s
            ORDER BY r.reservation_date DESC
        """, (session.get('username'),))
    
    reservations = cur.fetchall()
    

    # Преобразуем результат в список словарей для удобства в шаблоне
    reservations_list = [
        {
            'id': row[0],
            'username': row[1],
            'name': row[2],
            'study_group': row[3],
            'telegram': row[4],
            'reservation_goal': row[5],
            'reservation_date': row[6],
            'date_take_equipment': row[7],
            'reserve_status': row[8],
            'equipment_title': row[9],
            'equipment_type': row[10],
        }
        for row in reservations #if row[8] != 'Возвращено' and row[8] != 'Отклонено' and row[8] != 'Не возвращено'
    ]

    if session.get('role') == 'admin':
        # Для админа показываем все бронирования
        cur.execute("""
            SELECT r.id, u.username, u.name, u.study_group, u.telegram, r.reservation_goal, 

templates/add_equipment.html
{% extends 'base.html' %}

{% block title %}Добавить снаряжение{% endblock %}

{% block content %}
<div class="form-container">
    <h2>Добавить снаряжение</h2>
    <form method="POST" action="{{ url_for('equipment.add_equipment') }}">
        <label class="label">Тип:</label>
        <input type="text" name="type" required>

        <label class="label">Название:</label>
        <input type="text" name="title" required>

        <label class="label">Описание:</label>
        <input type="text" name="description">

        <label class="label">Количество:</label>
        <input type="text" name="amount">

        <button type="submit" class="btn">Добавить</button>
        <a href="{{ url_for('equipment.arenda') }}" class="btn gray">Отмена</a>
    </form>
</div>

<style>
    .form-container {
        width: 350px;
        margin: 40px auto;
        padding: 20px;
        background: rgba(255, 255, 255, 0.8);
        border-radius: 50px;
        text-align: center;
        border: 3px solid #0D60AE;
    }

    input {
        font-size: 1em;
        width: calc(100% - 20px);
        padding: 10px;
        margin-top: 8px;
        margin-bottom: 14px;
        border: 1px solid #ccc;
        border-radius: 50px;
        box-sizing: border-box;
    }

    h2 {
        margin-top: 0px;
        font-size: 28px;
        font-weight: bold;
        color: #0D60AE;
    }

    .label {
        font-size: 16px;
        color: #333;
        font-weight: bold;
        display: block;
        margin: 0 10px;
        text-align: left;
    }

    .btn {
        background-color: #0D60AE;
        color: white;
        border: none;
        padding: 12px 24px;
        font-size: 16px;
        margin: 10px;
        border-radius: 50px;
        cursor: pointer;
    }

    .btn:hover {
        background-color: #083a99;
    }
    .btn.gray {
        background-color: #6c757d;
    }
</style>
{% endblock %}

templates/arenda.html
{% extends 'base.html' %}

{% block title %}Аренда Снаряжения{% endblock %}

{% block content %}
<div class="container">
    <h1 class="heading">АРЕНДА СНАРЯЖЕНИЯ</h1>
    <div class="equipment-table">
        <table>
            <thead>
                <tr>
                    <th class="th-top-left">Тип</th>
                    <th>Название</th>
                    <th>Описание{% if role == 'admin' %}, Количество{% endif %}</th>
                    <th class="th-top-right">Действия</th>
                </tr>
            </thead>
            <tbody>
                {% for item in equipment %}
                <tr>
                    <td>{{ item.type }}</td>
                    <td>{{ item.title }}</td>
                    <td>{{ item.description }}{% if role == 'admin' %}, <strong>{{ item.amount }} шт.</strong>
                        {% endif %}
                    </td>
                    <td class="actions">
                        <a href="{{ url_for('reservation.reserve', equipment_id=item.id) }}" class="btn green">Забронировать</a>
                        {% if role == 'admin' %}
                            <a href="{{ url_for('equipment.edit_equipment', id=item.id) }}" class="btn blue">Редактировать</a>
                            <form id="deleteForm-{{ item.id }}" action="{{ url_for('equipment.delete_equipment', equipment_id=item.id) }}" method="POST" style="display:inline;">
                                <button type="button" class="btn red" onclick="showConfirm('Вы уверены, что хотите удалить {{ item.title | e }}?', 'deleteForm-{{ item.id }}')">Удалить</button>
                            </form>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <!-- Пагинация -->
        {% if total_pages > 1 %}
        <div class="pagination">
            {% if current_page > 1 %}
                <a href="{{ url_for('equipment.arenda', page=current_page-1) }}" class="pagination-btn">← Назад</a>
            {% endif %}
            
            <span class="page-info">Страница {{ current_page }} из {{ total_pages }}</span>
            
            {% if current_page < total_pages %}
                <a href="{{ url_for('equipment.arenda', page=current_page+1) }}" class="pagination-btn">Вперед →</a>
            {% endif %}
        </div>
        {% endif %}

        
            <div class="admin-actions">
                {% if role == 'admin' %}
                <a href="{{ url_for('equipment.add_equipment') }}" class="btn blue">Добавить снаряжение</a>
                {% endif %}
                <a href="{{ url_for('reservation.view_reservations') }}" class="btn gray">Все брони</a>
            </div>
        
    </div>

    <!-- Модальное окно подтверждения -->
    <div id="confirmModal" class="modal">
        <div class="modal-content">
            <p id="confirmMessage"></p>
            <div class="modal-actions">
                <button id="confirmYes" class="btn blue">Да</button>
                <button id="confirmNo" class="btn gray">Нет</button>
            </div>
        </div>
    </div>
</div>

<style>
    /* Стили для основного контента (оставляем без изменений) */
    .container {
        display: flex;
        flex-direction: column;
        align-items: center;
        margin-top: 40px;
        width: 95%;
        margin-left: auto;
        margin-right: auto;
    }
    
    .heading {
        font-size: 2.5em;
        color: #0D60AE;
        margin-bottom: 12px;
        margin-top: -40px;
        font-weight: bold;
    }
    
    .equipment-table {
        background: white;
        padding: 20px;
        border: 3px solid #0D60AE;
        border-radius: 40px;
        width: 95%;
        max-width: none;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
    }
    
    table {
        width: 100%;
        border-collapse: collapse;
        table-layout: fixed;
    }
    
    th, td {
        padding: 10px 15px;
        text-align: center;
        border-bottom: 1px solid #ddd;
    }

    th:nth-child(1) { width: 10%; }
    th:nth-child(2) { width: 15%; }
    th:nth-child(3) { width: 40%; }
    th:nth-child(4) { width: 30%; }

    .actions {
        text-align: center;
        padding-right: 25px;
        white-space: nowrap;
    }

    .actions .btn {
        margin-left: 5px;
        margin-right: 0;
    }
    
    th {
        background-color: #0D60AE;
        color: white;
        font-weight: normal;
    }
    
    .th-top-left {
        border-top-left-radius: 20px;
    }
    
    .th-top-right {
        border-top-right-radius: 20px;
    }
    
    .btn {
        padding: 8px 12px;
        border-radius: 20px;
        color: white;
        text-decoration: none;
        font-size: 1em;
        margin: 2px;
        display: inline-block;
        border: none;
        cursor: pointer;
        transition: background-color 0.3s;
    }
    
    .btn.green {
        background-color: #28a745;
    }
    .btn.green:hover {
        background-color: #218939;
    }
    
    .btn.red {
        background-color: #dc3545;
    }
    .btn.red:hover {
        background-color: #be2d3c;
    }
    
    .btn.blue {
        background-color: #007bff;
    }
    .btn.blue:hover {
        background-color: #036ddf;
    }
    
    .btn.gray {
        background-color: #78818a;
    }
    .btn.gray:hover {
        background-color: #646c73;    }
    
    .admin-actions {
        margin-top: 20px;
        text-align: center;
    }

    .pagination {
        margin-top: 20px;
        display: flex;
        justify-content: center;
        align-items: center;
        gap: 20px;
    }

    .pagination-btn {
        padding: 8px 16px;
        background-color: #0D60AE;
        color: white;
        text-decoration: none;
        border-radius: 20px;
        transition: background-color 0.3s;
    }

    .pagination-btn:hover {
        background-color: #083a99;
    }

    .page-info {
        font-size: 1.1em;
    }

    body {
        overflow-y: auto !important;
    }

    /* Стили для модального окна */
    .modal {
        display: none;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: rgba(0, 0, 0, 0.5);
        z-index: 1000;
    }

    .modal-content {
        background: white;
        padding: 20px;
        border: 3px solid #0D60AE;
        border-radius: 20px;
        width: 90%;
        max-width: 400px;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        text-align: center;
        font-family: "HSE Sans", sans-serif;
    }

    .modal-content p {
        font-size: 1.2em;
        color: #000000;
        margin: 0 0 20px 0;
    }

    .modal-actions {
        display: flex;
        justify-content: center;
        gap: 10px;
    }
    .modal-actions .btn {
        min-width: 120px; /* Задаем минимальную ширину кнопки */
        text-align: center; /* Центрируем текст внутри кнопки */
        font-size: 1.2em;
    }
</style>

<script>
    function showConfirm(message, formId) {
        // Показываем модальное окно
        const modal = document.getElementById('confirmModal');
        const messageElement = document.getElementById('confirmMessage');
        modal.style.display = 'block';
        messageElement.textContent = message;

        // Кнопка "Да"
        document.getElementById('confirmYes').onclick = function() {
            document.getElementById(formId).submit(); // Отправляем форму
        };

        // Кнопка "Нет"
        document.getElementById('confirmNo').onclick = function() {
            modal.style.display = 'none'; // Скрываем окно
        };
    }

    // Закрытие модального окна при клике вне его
    document.getElementById('confirmModal').onclick = function(event) {
        if (event.target === this) {
            this.style.display = 'none';
        }
    };
</script>

{% endblock %}

templates/edit_equipment.html
{% extends 'base.html' %}

{% block title %}Редактировать Снаряжение{% endblock %}

{% block content %}
<div class="container">
    <div class="edit-form">
        <h1 class="heading">Редактировать снаряжение</h1>
        <form method="POST" action="{{ url_for('equipment.edit_equipment', id=equipment.id) }}">
            <div class="form-group">
                <label for="type">Тип:</label>
                <input type="text" id="type" name="type" value="{{ equipment.type }}" required>
            </div>
            <div class="form-group">
                <label for="title">Название:</label>
                <input type="text" id="title" name="title" value="{{ equipment.title }}" required>
            </div>
            <div class="form-group">
                <label for="description">Описание:</label>
                <input type="text" id="description" name="description" value="{{ equipment.description }}">
            </div>
            <div class="form-group">
                <label for="description">Количество:</label>
                <input type="text" id="amount" name="amount" value="{{ equipment.amount }}">
            </div>
            <div class="form-actions">
                <button type="submit" class="btn blue">ОК</button>
                <a href="{{ url_for('equipment.arenda') }}" class="btn gray">Отмена</a>
            </div>
        </form>
    </div>
</div>

<style>
    .container {
        display: flex;
        justify-content: center;
        margin: 0;
        padding-top: 80px; /* Отступ сверху, чтобы форма была ближе к верху */
    }

    .edit-form {
        /* background: white;
        padding: 20px;
        border: 3px solid #0D60AE;
        border-radius: 20px;
        width: 90%;
        max-width: 400px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        text-align: center; */

        width: 350px;
        margin: -40px auto;
        padding: 20px;
        background: rgba(255, 255, 255, 0.8);
        border-radius: 50px;
        text-align: center;
        border: 3px solid #0D60AE;
    }

    .heading {
        font-size: 2em;
        color: #0D60AE;
        margin-bottom: 20px;
        margin-top: 0px;
        font-weight: bold;
    }

    .form-group {
        margin-bottom: 15px;
        text-align: left;
    }

    .form-group label {
        font-size: 16px;
        color: #333;
        font-weight: bold;
        display: block;
        margin: 0 10px;
        text-align: left;
    }

    /* .form-group input,
    .form-group textarea {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 1em;
        box-sizing: border-box;
    } */

    .form-group input {
        font-size: 1em;
        width: calc(100% - 20px);
        padding: 10px;
        margin-top: 8px;
        margin-bottom: 14px;
        border: 1px solid #ccc;
        border-radius: 50px;
        box-sizing: border-box;
    }
    


    .form-actions {
        display: flex;
        justify-content: center;
        gap: 10px;
        margin-top: 20px;
    }

    .btn {
        background-color: #0D60AE;
        color: white;
        border: none;
        padding: 12px 24px;
        font-size: 16px;
        margin: 10px;
        border-radius: 50px;
        cursor: pointer;
        
    }

    .btn:hover {
        background-color: #083a99;
    }
    .btn.blue {
        min-width: 100px;
    }
    .btn.gray {
        background-color: #6c757d;
    }
</style>
{% endblock %}